name: Trigger auto deployment for student-social-website-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/student-social-website-container-AutoDeployTrigger-dd98d1c5-5771-49b9-a9c7-9e0045b8f2f8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STUDENTSOCIALWEBSITECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STUDENTSOCIALWEBSITECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STUDENTSOCIALWEBSITECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: studentsocialcontainerregister.azurecr.io
          registryUsername: ${{ secrets.STUDENTSOCIALWEBSITECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STUDENTSOCIALWEBSITECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: student-social-website-container
          resourceGroup: StudentSocialPlatform
          imageToBuild: studentsocialcontainerregister.azurecr.io/student-social-website-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


